---
name: "tagged-release"
env:
  APP_NAME: static

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      
      - run: mvn clean javadoc:javadoc package install | echo "done!"
      
      
      - run: cp target/*.jar .
      
      - run: zip -r javadoc.zip target/site/apidocs/
      
    
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
            *.jar
            javadoc.zip

